feat(icons): introduce title props on icons for additional info on hover
MTES-MCT/monitor-ui pull request #1118
Opened 2024-03-21 13:21 UTC by lwih

## Description

Dans le cadre du nouveau statut de mission, on doit maintenant montrer une sorte de title sur les icones comme dans ce screenshot:
<img width="1929" alt="Screenshot 2024-03-21 at 14 13 19" src="https://github.com/MTES-MCT/monitor-ui/assets/4593884/cd9e5cb2-b162-41f6-b0e4-605be8b935ec">

La solution que j'ai retenu, c'était d'ajouter une balise `<title>` dans le SVG dans le script de génération des Icon components. 
J'ai aussi ajouté une prop optionnelle `title` pour les icônes.
L'effet hover n'est pas déclenché quand title est undefined ou empty string.

Ouvert à tout type de feedback pour savoir si c'était le bon endroit pour mettre ça et si je m'y suis bien pris.

PS: déso pour la longueur de la PR mais il a fallu regen toutes les icones. Les fichiers importants sont autour du script de generation.

## Preview URL

_Waiting for deployment..._

2024-03-24 21:12 UTC, ivangabriele commented on scripts/icons/generateIcons.js
> +    .replace(/\<\/svg\>/, "<title>{title}</title></svg>")
Ah oui en effet, ça serait mieux de le mettre sur `IconBox` directement dans le template, le SVG en héritera au survol :

```
import { IconBox } from '../elements/IconBox'

import type { IconProps } from '../types/definitions'

export const /*ICON_NAME*/ = ({ color, size, title, ...nativeProps}: IconProps) => (
  <IconBox $size={size} $color={color} title={title}>
    /*ICON_SVG_SOURCE*/
  </IconBox>
)
```

2024-03-24 21:14 UTC, ivangabriele requested changes
Répondu dans le commentaire ^^.

2024-03-25 10:03 UTC, lwih commented on scripts/icons/generateIcons.js
> +    .replace(/\<\/svg\>/, "<title>{title}</title></svg>")
Smarter indeed, j'ai corrigé.

2024-03-25 14:19 UTC, ivangabriele approved these changes

2024-03-25 15:06 UTC, merged

2024-03-25 15:49 UTC, ivangabriele commented
:tada: This PR is included in version 13.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@mtes-mct/monitor-ui/v/13.10.0)
- [GitHub release](https://github.com/MTES-MCT/monitor-ui/releases/tag/v13.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: