feat(fields): add isReadOnly prop on multiRadio component and add custom style for plaintext
MTES-MCT/monitor-ui pull request #786
Opened 2023-09-19 07:12 UTC by claire2212

Customize multiRadio style for readOnly mode

![Capture d’écran 2023-09-19 à 09 11 49](https://github.com/MTES-MCT/monitor-ui/assets/23258718/95988924-6308-4c0a-b34c-31e2d92c48a0)

## Related Pull Requests & Issues

- MTES-MCT/monitorenv#827

## Preview URL

_Waiting for deployment..._

2023-09-19 09:09 UTC, lwih approved these changes
Ca me parait bien 🚀

2023-09-22 12:21 UTC, ivangabriele requested changes

2023-09-22 12:21 UTC, ivangabriele commented on src/fields/MultiRadio.tsx
>    name,
`useFieldUndefineEffect(isUndefinedWhenDisabled && disabled, onChange)` =>
`useFieldUndefineEffect(isUndefinedWhenDisabled && !isReadOnly && disabled, onChange)`

2023-09-25 08:19 UTC, ivangabriele approved these changes

2023-09-25 08:20 UTC, merged

2023-09-25 08:28 UTC, ivangabriele commented
:tada: This PR is included in version 10.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@mtes-mct/monitor-ui/v/10.0.0)
- [GitHub release](https://github.com/MTES-MCT/monitor-ui/releases/tag/v10.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: